export const DEPARTMENTS = [
    "IT", "DOCTOR", "NURSE", "HR", "LAB", "RT TECH", "PHARMACY",
    "TELECALLER", "FRONT OFFICE", "SECURITY", "ELECTRICIAN", "ACCOUNTS",
    "NURSING", "HOUSE KEEPING", "DENSIST CONSULTANT", "COOK"
  ];